#!/usr/bin/env bash

CONFIG_PATH=~/.config/cmdlatex/config.tex

cp cmdlatex.sh ~/.local/bin/cmdlatex
echo "Copied executable to ~/.local/bin/cmdlatex."

mkdir -p ~/.config/cmdlatex
echo "Created directory ~/.config/cmdlatex/ if it did not already exist."

if ! test -f $CONFIG_PATH; then
    echo "\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{newpxtext}
\usepackage{mathpartir}
\usepackage{stmaryrd}
\usepackage{varwidth}" > $CONFIG_PATH
echo "Created config file ~/.config/cmdlatex/config.tex with default content."
fi
echo "Installation finished!"
