#!/usr/bin/env bash

cp cmdlatex.sh ~/.local/bin/cmdlatex
mkdir -p ~/.config/cmdlatex
echo "\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{newpxtext}
\usepackage{mathpartir}
\usepackage{stmaryrd}
\usepackage{varwidth}" > ~/.config/cmdlatex/config.tex
